config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new

  end

  def create
    @article = Article.new article_params
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def index
    @articles = Article.all
  end

  def show
    puts params
    @article = Article.find(params[:id])
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.haml
.row
  .col-12.text-center
    %h1= "Listing Articles"

.row
  .offset-3.col-6
    %table.table
      %thead
        %tr
          %th
            id
          %th
            Title
          %th
      %tbody
      - @articles.each do |article|
        %tr
          %td
            = article.id
          %td
            = article.title
          %td
            = link_to  article.id, article,  class: "btn btn-primary btn-block"
.row
  .offset-3.col-6
    = link_to 'New Article', new_article_path, class: "btn btn-info btn-block"

app/views/articles/new.html.haml
.row
  .col-12.text-center
    .h1
      New Article
.row
  .col-3
  .col-6
    = form_for :article, url: :articles, local: true do |f|
      .form-group.row
        .col-2.col-form-label
          = label :article, :title, "Title"
        .col-10
          = text_field :article, :title, class: "form-control"
      .form-group.row
        .col-2.col-form-label
          = label :article, :text, "Text"
        .col-10
          = text_area :article, :text, class: "form-control"
      .form-group.row
        .offset-3.col-6
          = button_tag :submit, class: "btn btn-primary btn-block"
  .col-3

app/views/articles/show.html.haml
.row
  .col-12.text-center
    %h1= "\##{@article.id}"
.row
  .offset-3.col-6
    %strong= "Title"
    %p= @article.title
.row
  .offset-3.col-6
    %strong= "Text"
    %p= @article.text
.row
  .offset-4.col-4
    = link_to 'Return to List', articles_path, class: "btn btn-warning btn-block"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/index.html.haml
.h1
  Hello